# Basic tmux configuration
set -g mouse on
set -g history-limit 50000

# easier pane splitting
bind | split-window -h
bind - split-window -v

# reload config
bind r source-file ~/.tmux.conf \; display-message 'tmux config reloaded'
