# Basic tmux configuration
set -g mouse on
set -g history-limit 50000

# easier pane splitting
bind | split-window -h
bind - split-window -v

# reload config
bind r source-file ~/.tmux.conf \; display-message 'tmux config reloaded'

# Improve status bar
set -g status-position top
set -g status-justify left
set -g status-style 'bg=#3c3836,fg=#ebdbb2'
set -g status-left ''
set -g status-right '#[fg=#282828,bg=#b8bb26,bold] %Y-%m-%d | %H:%M #[default]'
set -g window-status-current-style 'fg=#282828,bg=#fabd2f,bold'
set -g window-status-current-format ' #I #W '
set -g window-status-style 'fg=#ebdbb2,bg=#504945'
set -g window-status-format ' #I #W '

# Recommend adding TPM (Tmux Plugin Manager) for plugins like tmux-resurrect
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
